### ISSUE TITLE
Create `cbctl` that can run named Cloud Build triggers

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/gcp-config#15]
Derived from comments on https://github.com/m-lab/siteinfo/pull/100

> I suggest that we create a new command, perhaps cbctl, with a subcommand "trigger" that accepts a trigger ID. This command should live in the gcp-config repo. My vision is to create a standard set of containers that will exist in our projects by default that we can just reference in the cloudbuild.yamls of other repos (like this one).
> 
> The other operations that cbctl would support is registering the trigger definitions for the standard workflow that we support between sandbox, staging, and prod using a uniform name, for a new (or existing) repo. Basically to remove the manual steps for creating build configs through GCP web console.

**Comment by nkinkade** [comment]
@stephen-soltesz: I believe this issue was resolved, and `cbctl` now exists and is in use. If this is correct, would you close this issue?

**Comment by stephen-soltesz** [comment]
It's probably close enough. I'd had a fantasy that the webflow steps could be done through the CLI also, but that's a higher bar and the cbctl help text includes necessary links and warnings. so, yes I think we've satisfied the spirit of this issue.

**Comment by nkinkade** [comment]
Out of curiosity, is it even possible to connect a Github repo to Cloud Build in some other way than through the GCP Web Console? I looked around earlier today, but didn't immediately see that it was even possible.

**Comment by stephen-soltesz** [comment]
Also a good question. I don't know if it's even possible in principle.
