### ISSUE TITLE
Pusher transfers do not currently include bismark and revtr

### ISSUE THREAD

**Issue by gfr10598** [m-lab/gcp-config#37]
Currently, these are excluded from transfers.  It seems like we should be transferring everything.

If we want these to be backed up elsewhere, we should add more transfer rules.

**Comment by laiyi-ohlsen** [comment]
Bismark not currently on platform

**Comment by pboothe** [comment]
If the data is only in sandbox: delete it.

**Comment by gfr10598** [comment]
sandbox bismark data should be deleted

**Comment by gfr10598** [comment]
Data is also in pusher-mlab-oti, and needs to be cleaned up with a lifecycle rule.  Also see https://github.com/m-lab/dev-tracker/issues/650

**Comment by stephen-soltesz** [comment]
revtr is now included in transfer.
