### ISSUE TITLE
Cloud Builds are broken in mlab-oti (daily-archive-transfers.yaml)

### ISSUE THREAD

**Issue by nkinkade** [m-lab/gcp-config#40]
The build error is:

```
Step #1: 2021/02/08 18:30:06 Failed to sync (error: googleapi: Error 400: Service account storage-transfer-13271960596232968425@partnercontent.gserviceaccount.com does not have required permissions {storage.objects.list, storage.objects.delete} for bucket pusher-mlab-oti., failedPrecondition)
Step #1: 2021/02/08 18:30:06 error: pid:9 code:1 err:exit status 1
Finished Step #1
ERROR
ERROR: build step 1 "gcp-config-cbif" failed: step exited with non-zero status: 1
```

This looks rather like the service account or GCS bucket being used for this build in production is lacking some permissions that may have been manually configured in sandbox and staging (where builds are working). @stephen-soltesz noted that @gfr10598 had been making some changes to this repo which could possibly have affected this.

**Comment by laiyi-ohlsen** [comment]
@stephen-soltesz checking if this is still relevant.

**Comment by nkinkade** [comment]
I believe that @stephen-soltesz and I resolved this some weeks ago. Closing. @stephen-soltesz can reopen if he thinks this is incorrect.
